"""Module 03 — pre-existing data.

Primary path: download REAL Esri World Imagery XYZ tiles for the pilot site,
stitch them into an orthomosaic PNG + ESRI world file, and record provenance
provider / attribution / licence note in `provenance.json`. OSM linear context
(roads/waterways) is retried best-effort and vendored; when it is unavailable
the survey still runs (the PRD only *recommends* OSM road layer).

NOT generated by this project: the imagery itself. Everything downstream of it
(demo layers marked in provenance) is generated as the PRD allows.
"""
from __future__ import annotations

import io
import json
import math
import time
from datetime import date, datetime, timezone
from pathlib import Path

import numpy as np
import requests
from PIL import Image

from ..config import SiteCfg, DATA_DIR
from ..raster import save_png, tile_affine, write_provenance

UA = {"User-Agent": "RuralLandResurveyTriage/0.1 (research prototype)"}


def _tile_range(z: int, lat: float, lon: float, n: int) -> tuple[int, int]:
    nn = 2 ** z
    xf = (lon + 180.0) / 360.0 * nn
    yf = (1 - math.asinh(math.tan(math.radians(lat))) / math.pi) / 2.0 * nn
    x0 = int(xf) - n // 2
    y0 = int(yf) - n // 2
    return x0, y0


def fetch_orthomosaic(site: SiteCfg, village_id: str, z: int | None = None,
                      tiles: int | None = None, retries: int = 3) -> dict:
    """Download + stitch real tiles -> data/imagery/{id}_ortho.{png,pgw,json}."""
    z = z or site.zoom
    n = tiles or site.tiles
    x0, y0 = _tile_range(z, site.lat, site.lon, n)
    canvas = Image.new("RGB", (n * 256, n * 256), (0, 0, 0))
    got, tried = 0, []
    for j in range(n):
        for i in range(n):
            url = site.tile_url.format(z=z, x=x0 + j, y=y0 + i)
            for attempt in range(retries):
                try:
                    r = requests.get(url, timeout=40, headers=UA)
                    if r.status_code == 200 and len(r.content) > 1200:
                        im = Image.open(io.BytesIO(r.content)).convert("RGB")
                        if np.asarray(im).std() >= 6:      # skip blank tiles
                            canvas.paste(im, (j * 256, i * 256))
                            got += 1
                            tried.append(url)
                            break
                    time.sleep(0.6 * (attempt + 1))
                except Exception:
                    time.sleep(0.8 * (attempt + 1))
    if got == 0:
        raise RuntimeError("no imagery tiles retrieved — check network")

    img = np.asarray(canvas)
    aff = tile_affine(z, x0, y0, img.shape[1], img.shape[0])
    out_dir = DATA_DIR / "imagery"
    png_path = out_dir / f"{village_id}_ortho.png"
    save_png(img, png_path)
    aff.write_world_file(out_dir / f"{village_id}_ortho.pgw")
    res_cm = aff.resolution_m_per_px(site.lat) * 100.0
    provenance = {
        "provider": "Esri World Imagery (ArcGIS Online)",
        "tile_url_template": site.tile_url,
        "attribution": site.attribution,
        "licence_note": "Esri basemap tiles — attribution required; not survey-grade.",
        "zoom": z, "tiles": [n, n], "tiles_retrieved": got,
        "tile_range": {"x0": x0, "y0": y0},
        "fetched_at": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        "generated_by_this_project": False,
        "note": "Externally sourced imagery (PRD Module 03 'pre-existing data'). "
                "Acquisition date not published by provider; capture_date records "
                "the retrieval date.",
        "resolution_cm_per_px": round(res_cm, 3),
        "bounds_wgs84": aff.bounds_wgs84(img.shape[1], img.shape[0]),
    }
    write_provenance(out_dir / f"{village_id}_ortho.json", provenance)
    return {
        "path": f"imagery/{village_id}_ortho.png",
        "affine": aff,
        "image": img,
        "resolution_cm_per_px": round(res_cm, 3),
        "provenance": provenance,
        "capture_date": date.today().isoformat(),
        "bounds": aff.bounds_wgs84(img.shape[1], img.shape[0]),
    }


def load_cached(village_id: str) -> dict | None:
    """Load a previously fetched orthomosaic + affine + provenance from disk."""
    from ..raster import WorldFileAffine, load_png
    png = DATA_DIR / "imagery" / f"{village_id}_ortho.png"
    if not png.exists():
        return None
    img = load_png(png)
    aff = WorldFileAffine.read_world_file(png.with_suffix(".pgw"))
    prov = json.loads(png.with_suffix(".json").read_text(encoding="utf-8"))
    res_cm = prov.get("resolution_cm_per_px") or aff.resolution_m_per_px(20.0) * 100.0
    return {
        "path": f"imagery/{village_id}_ortho.png",
        "affine": aff,
        "image": img,
        "resolution_cm_per_px": round(float(res_cm), 3),
        "provenance": prov,
        "capture_date": prov.get("fetched_at", "")[:10],
        "bounds": aff.bounds_wgs84(img.shape[1], img.shape[0]),
    }


def fetch_osm_context(lat: float, lon: float, radius_m: int = 2000) -> dict | None:
    """Best-effort OSM context around the pilot extent, vendored on success.

    Queries BOTH linear features (highway/waterway/canal, for the map
    overlay) AND farmland polygons (landuse=farm/farmland/meadow/orchard
    + crop=yes, for the Tier-1 real-observation layer in
    `pipeline/realobs.py`). Linear results keep the legacy
    `context/osm_linear.json` path/shape; farmland is vendored separately at
    `context/osm_farmland.geojson` and never blocks the survey when absent.
    Later calls return the cached files so runtime never needs the network.
    """
    lin_path = DATA_DIR / "context" / "osm_linear.json"
    farm_path = DATA_DIR / "context" / "osm_farmland.geojson"
    if lin_path.exists():
        try:
            return json.loads(lin_path.read_text(encoding="utf-8"))
        except (json.JSONDecodeError, OSError):
            pass
    lin_query = f"""
    [out:json][timeout:60];
    (
      way(around:{radius_m},{lat},{lon})["highway"];
      way(around:{radius_m},{lat},{lon})["waterway"];
      way(around:{radius_m},{lat},{lon})["canal"];
    );
    out geom;"""
    farm_query = f"""
    [out:json][timeout:60];
    (
      way(around:{radius_m},{lat},{lon})["landuse"~"^(farm|farmland|meadow|orchard|plant_nursery)$"];
      relation(around:{radius_m},{lat},{lon})["landuse"~"^(farm|farmland|meadow|orchard|plant_nursery)$"];
      way(around:{radius_m},{lat},{lon})["crop"];
    );
    out geom;"""
    out = None
    for mirror in ("https://overpass-api.de/api/interpreter",
                   "https://overpass.kumi.systems/api/interpreter"):
        try:
            r = requests.post(mirror, data={"data": lin_query},
                              timeout=60, headers=UA)
            if r.status_code == 200:
                data = r.json()
                out = {"elements": data.get("elements", []),
                       "source": mirror,
                       "fetched_at": datetime.now(timezone.utc).isoformat(timespec="seconds"),
                       "generated_by_this_project": False}
                lin_path.parent.mkdir(parents=True, exist_ok=True)
                lin_path.write_text(json.dumps(out), encoding="utf-8")
                break
        except Exception:
            continue
    # Farmland polygons: best-effort, never block the survey.
    if out is not None and not farm_path.exists():
        for mirror in ("https://overpass-api.de/api/interpreter",
                       "https://overpass.kumi.systems/api/interpreter"):
            try:
                r = requests.post(mirror, data={"data": farm_query},
                                  timeout=60, headers=UA)
                if r.status_code == 200:
                    feats = _overpass_to_geojson(r.json().get("elements", []))
                    farm_path.parent.mkdir(parents=True, exist_ok=True)
                    farm_path.write_text(json.dumps({
                        "type": "FeatureCollection", "features": feats,
                        "source": mirror,
                        "fetched_at": datetime.now(timezone.utc).isoformat(
                            timespec="seconds"),
                        "generated_by_this_project": False,
                    }), encoding="utf-8")
                    break
            except Exception:
                continue
    return out


def _overpass_to_geojson(elements: list[dict]) -> list[dict]:
    """Overpass `out geom` ways/relations -> GeoJSON Polygon features."""
    nodes: dict[int, tuple[float, float]] = {}
    for el in elements:
        if el.get("type") == "node" and "lon" in el and "lat" in el:
            nodes[el["id"]] = (el["lon"], el["lat"])
    feats: list[dict] = []
    for el in elements:
        tags = el.get("tags", {}) or {}
        geom = el.get("geometry", []) or []
        ring = ([(p["lon"], p["lat"]) for p in geom]
                if geom else
                [nodes[n] for n in el.get("nodes", []) if n in nodes])
        if len(ring) < 4 or ring[0] != ring[-1]:
            continue
        feats.append({"type": "Feature", "geometry": {
            "type": "Polygon", "coordinates": [ring]},
            "properties": {"landuse": tags.get("landuse"),
                           "crop": tags.get("crop"),
                           "name": tags.get("name")}})
    return feats
